[package]
name = "wod"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.30", features = ["derive"] }
strsim = "0.11.1"

[dev-dependencies]
tempfile = "3.19.1"
